version: "3.5"

services:
    database:
        extends:
            file: ./docker/postgres/compose.yaml
            service: database
    frontend:
        extends:
            file: ../mocap-frontend/compose.yaml
            service: frontend
        depends_on:
            - backend
            - keycloak
    backend:
        extends:
            file: ../mocap-backend/compose.yaml
            service: backend
        depends_on:
            - keycloak
            - database
    keycloak:
        extends:
            file: ../mocap-keycloak/compose.yaml
            service: keycloak
    nginx:
        extends:
            file: ./docker/nginx/compose.yaml
            service: nginx
        depends_on:
            - frontend
            - backend
            - keycloak
networks:
    mocap:
        driver: bridge
