version: "3.5"

services:
    database:
        extends:
            file: ./docker/postgres/compose.yaml
            service: database
    frontend:
        extends:
            file: ../mocap-frontend/compose.yaml
            service: frontend
    backend:
        extends:
            file: ../mocap-backend/compose.yaml
            service: backend
    keycloak:
        extends:
            file: ../mocap-keycloak/compose.yaml
            service: keycloak
    nginx:
        extends:
            file: ./docker/nginx/compose.yaml
            service: nginx
networks:
    mocap:
        driver: bridge
