version: "3.5"

services:
    nginx:
        image: mocap/nginx
        container_name: mocap-nginx
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - ../../.env.production
            - ../../.env.production.local
        networks:
            - mocap
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
            - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
networks:
    mocap:
        external: true
